### ISSUE TITLE
Can't import `ts2307`

### ISSUE THREAD

**Issue by PorcoRosso85** [option-t/option-t#1991]
### image
![image](https://github.com/option-t/option-t/assets/40359643/bf9db7c0-f0b1-4335-adf8-151da0872328)
![image](https://github.com/option-t/option-t/assets/40359643/43c8c905-feaf-4cfa-87fb-6a8d3b3bac6c)

### system
```
 node -v
v21.5.0
 pnpm -v
8.10.5
 which node
/home/user/pjs/go_node/.devbox/nix/profile/default/bin/node
which pnpm
/home/user/pjs/go_node/.devbox/nix/profile/default/bin/pnpm

Info: New devbox available: 0.8.2 -> v0.8.7. Please run `devbox version update`.
0.8.2

wsl
ubuntu22.04
```

Hi.
I can't import by `ts2307`
As image, I've tried importing with the most minimal architecture using `pnpm`.
Any thoughts?

**Comment by PorcoRosso85** [comment]
The report

I've tried importing with Codesandbox `vite + ts` kit.
`option-t` is importable.

[codesandbox](https://codesandbox.io/p/devbox/objective-turing-lzqgll?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls28inf00007356gp5ybhgif%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls28inf00002356g7e43z377%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls28inf00005356ge25a965w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls28inf00006356g7trv7wfp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls28inf00002356g7e43z377%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls28inez0001356g7xlg02ev%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%257D%255D%252C%2522id%2522%253A%2522cls28inf00002356g7e43z377%2522%252C%2522activeTabId%2522%253A%2522cls28inez0001356g7xlg02ev%2522%257D%252C%2522cls28inf00006356g7trv7wfp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls28inf00006356g7trv7wfp%2522%257D%252C%2522cls28inf00005356ge25a965w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls28inf00003356g8zhzsrhc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cls28inf00004356g8ssebh6m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls28eam90007dxf904ya4o2c%2522%257D%255D%252C%2522id%2522%253A%2522cls28inf00005356ge25a965w%2522%252C%2522activeTabId%2522%253A%2522cls28inf00003356g8zhzsrhc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by PorcoRosso85** [comment]
Let me add my env to reproduce

https://github.com/PorcoRosso85/option_t/tree/main

**Comment by tetsuharuohzeki** [comment]
@PorcoRosso85 

I suspect your project need to setup tsconfig.json correctly and set `--moduleResolution` option properly.
see https://github.com/option-t/option-t?tab=readme-ov-file#caution

Please feel free to reopen this.
