### ISSUE TITLE
Add Infer utility for PlainResult

### ISSUE THREAD

**Issue by totto2727** [option-t/option-t#2362]
Hello!

## Overview

I want to infer type arguments of type `Ok` or `Err` from type `PlainResult`.

## Proposal

How about adding the following type utility?

```ts
import { Result as R } from "option-t/plain_result/namespace";

type InferOk<T extends R.Result<unknown, unknown>> = T extends R.Ok<infer O> ? O : never;
type InferErr<T extends R.Result<unknown, unknown>> = T extends R.Err<infer E> ? E : never;
```

## Supplemental

To prevent inferred types from being nullable, I verify that they are Ok and Err types with Conditional Types.
I assume this is due to the fact that `Ok.err` is `null` and `Err.val` is `null`.
I have confirmed that the appropriate inference is made when the corresponding part of the type definition is replaced with `never`.

If the following PRs are merged, we can make a simpler implementation as follows.

https://github.com/option-t/option-t/pull/2245

```ts
type InferOk<T> = T extends R.Result<infer OK, unknown> ? OK : never;
type InferErr<T> = T extends R.Result<unknown, infer ERR> ? ERR : never;
```

**Comment by tetsuharuohzeki** [comment]
I understand this kind of utilities is useful for some specific scenarios, for example, the external library returns a value wrapped by our `Result<T, E>` and contains something typed with internal type that does not have any way to import by a library user, but I think it's better to export an actual type (`O` or `E`) directly  instead of using `infer`. In such case, it's foundamental design bug of the library that expose a type which user cannot import.

On top of that, why do you need to infer the contained type from `Result<T, E>`?

**Comment by totto2727** [comment]
> On top of that, why do you need to infer the contained type from Result<T, E>?

Because the current implementation will always result in a nullable inference result.

[TS Playground](https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBDAnmYcBKwDOBXANjAHgBUAaOAUQD44BeOAeQGtjqAfCqKAqgbgCg+oSLDgBLAHYxgUAGYBDAMaomBCNnhFqAbz5w9cKMDkATCONyI4ERgC4EUbMH76DR0+csA3ObjtFn+gD0gXBEABaimHAABuJ4uNFiUQC2oiDAxmKSEAhhqEgoVjK5qNHSUIlgUBAosJYQxQWl5JzRAHS6+oYmZhZw5XZxuLj8AL4CQtDwElKyiqgtXGrwVHA6Lt3ufdZ28riYTp16waERUbHxiZFwqemZMzkweQjIqA0lMd4JcFU10khFF6FaJMdpHVw9DxwL6DeIBPSbXqWAYUMYCJpwACCtDgAElxDJpCoMDh8ARMDAoBIAOYkOLJABG0kolHRrzxBKJzE0OKI-RAUnExiiJLwhAkhKgDAA0mRsOJGOIIAB3cTUAD8Mrgg2Anmk-Ax+MlixYvP5guF6CwYoI8sVKvEZAl0goaDQGtdaG1cHEuv1AiAA)

![Image](https://github.com/user-attachments/assets/13f57f88-c950-46d9-8951-e7b12c32788e)

![Image](https://github.com/user-attachments/assets/c1ab46fe-cdcf-4a5a-88f9-46d16598586e)


I assume that the problem is due to the following implementation.
By restricting it to the `Ok` and `Err` types, this `null` can be excluded from the inference results.

```ts
export type Result<T, E> = Ok<T> | Err<E>;

export interface Ok<out T> {
    readonly ok: true;
    readonly val: T;
    // This `null` is mixed into the type of the `err` property of type `Err`.
    readonly err: null;
}

export interface Err<out E> {
    readonly ok: false;
    // This `null` is mixed into the type of the `val` property of type `Ok`.
    readonly val: null;
    readonly err: E;
}
```

**Comment by totto2727** [comment]
When implementing a utility that extends `option-t`, it was defined and used internally.

https://github.com/totto2727-org/option-t-safe-try/blob/f0a02967f35e21607f4b8e4e3c68fa3ff5a73e1e/main.ts#L34-L38

Personally, I was happy to see it defined upstream, since I use this function relatively often, so I raised an Issue.

However, I also understand what you are saying.
Would you prefer the direction of defining it internally in my project?

**Comment by tetsuharuohzeki** [comment]
Thank you for your additional explanation.

> Would you prefer the direction of defining it internally in my project?

I think it would be better that.

I would like to behave to be careful to introduce a new API, especially if it allows some kinds of bad habit.
Additionally, IMO, I think also that it's simple and robust to write a type annotation explicitly for the place of a function signature as like as Rust to avoid bloat about type inference. It sometimes would be a redundant for TypeScript that works types a exist code incrementally but works as expected.

This does not decide that we will never introduce your proposed APIs,  but it's not the time to do it now, I think.

It might be good to add them as idiom as a part of https://github.com/option-t/option-t/tree/main/docs/idiom until we escalate this to a part of this package.

**Comment by totto2727** [comment]
Thank you for your polite explanation of the policy!

It certainly looks good to add it as an idiom.

I will submit a PR to add idioms later.
