### ISSUE TITLE
Proposal: pipe function

### ISSUE THREAD

**Issue by Bear-03** [option-t/option-t#2418]
Hello.

I am using `option-t` in the backend of a NextJS project and I am liking it a lot so far, but I have encoutered this situation multiple times now:

```js
const currentSession = await getCurrentSession();
const session = await R.orElseAsync(currentSession, async (_e) => await createSession(user.id))
const pair = R.map(session, (session) => ({ session, user }));
return R.mapErr(pair, (_e) => UserError.SessionError);
```

This snippet is really cumbersome; I am forced to define variable names for values that will only be relevant until the next line comes, cluttering the scope.

I understand that with the new pipeline operator proposal, this could be done in a much simpler way, like so:

```js
return await getCurrentSession()
    |> await R.orElseAsync(%, async (_e) => await createSession(user.id))
    |> R.map(%, (session) => ({ session, user }));
    |> R.mapErr(%, (_e) => UserError.SessionError);
```

But until the proposal is accepted, I feel like it would be convenient to have a `pipe` function (with both sync and async support) to improve the readability of the code when chaining operations.

```js
return await pipe(
    await getCurrentSession(),
    (s) => R.orElseAsync(s, async (_e) => await createSession(user.id)),
    (s) => R.map(s, (session) => ({ session, user })),
    (p) => R.mapErr(p, (_e) => UserError.SessionError),
);
```

This is much cleaner than the current approach, and it is also much closer to the pipeline operator code, which means that it would be easier to refactor the code once the proposal lands.

I see that this was implemented in the past in #380, but it was discarded after the change to the new treeshakeable API. It would be beneficial to bring that code back, at least until the pipeline operator is usable.

**Comment by tetsuharuohzeki** [comment]
Thank you for your idea.

But I'm sorry, I think this kind of function is not our business.

This usecase should be covered by:

1.  pipeline operator native syntax.
    - I still believe that proposal would advance in next several years :)
1. Or other library providing such feature.
